# Assignment 2 – NumPy

## Problem Statement:
You work in XYZ Corporation as a Data Analyst. Your corporation has told you to
use the NumPy package and do some tasks related to that.
## Tasks To Be Performed:
1. Create a 3x3 matrix array with values ranging from 2 to 10.
2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]
3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]
4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.
5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1
Perform the following tasks:
- a. Extract the 1st row from the array
- b. Extract the last element from the array


In [1]:
import numpy as np

In [10]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [22]:
arr = np.array([])
n = int(input("Enter no. of elements: "))
for i in range(n):
    arr = np.append(arr, int(input())).astype('float')
print(arr)

Enter no. of elements: 5
1
2
3
4
5
[1. 2. 3. 4. 5.]


In [37]:
a = np.array([10, 20, 30])
a = np.append(a, [40, 50, 60, 70, 80, 90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])
sumArray = a+b
sumArray

array([5, 7, 9])

In [41]:
array1 = np.arange(10,91,10).reshape(3,3)
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [42]:
array1[0]

array([10, 20, 30])

In [47]:
array1[-1,-1]

90